# The URL the site will be built for
base_url = "https://pigreco.luogoideale.org/dev_branches/zola-migration/"

# The language of this website
default_language = "it"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    { name = "activity" },
    { name = "pubblico" },
]

[extra]
# Put all your custom variables here
# 

[extra.taxonomies.activity]
	[extra.taxonomies.activity.animazione]
	name = "Animazione Matematica"
	description = """
        Occasioni per giocare e divertirsi,
        rivolte a tutti: dai più piccoli al pubblico adulto,
        per affrontare la matematica da un nuovo punto di vista.
    """

	[extra.taxonomies.activity.incontri]
	name = "Inconti con la matematica"
	description = """
        Conferenze informali, rivolte agli studenti della scuola
        secondaria e al grande pubblico per fornire spunti,
        approfondimenti e curiosità.
    """

	[extra.taxonomies.activity.percorsi]
	name = "Percorsi per le scuole"
	description = """
    Laboratori dedicati alle classi scuola dell’infanzia, primaria e secondaria per approfondire argomenti del programma scolastico (ma non solo!) coinvolgendo tutti gli alunni.
    """

	[extra.taxonomies.activity.altro]
	name = "#math"
	description = """
    Alcune delle nostre iniziative per contribuire alla diffusione della matematica nel mondo (reale e virtuale) con divertimento e simpatia.
    """
