name: Update flake inputs

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-flake-inputs:
    runs-on: ubuntu-latest
    steps:
      # Get nix
      - uses: cachix/install-nix-action@v31
        with:
          # Token is used to fetch nixpkgs using the github API and avoid rate limit
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      # Get the repo
      - uses: actions/checkout@v4

      - name: Update flake inputs
        run: |
          nix flake update sagome

      - name: Commit and push
        run: |
          BRANCH="update-flake-inputs/$(date -u +%Y%m%d-%H%M%S)"
          git config user.name "pigreco-bot"
          git config user.email "webmaster@luogoideale.org"
          git checkout -b "$BRANCH"
          git commit -am "chore: flake updated"
          git push origin "$BRANCH"
          echo "BRANCH=$BRANCH" >> "$GITHUB_ENV"

      - name: Create PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Wait a bit so github should be ready to create the PR
          sleep 3
          gh pr create \
            --base main \
            --head "$BRANCH" \
            --title "chore: nix flake update" \
            --body "This automated PR updates flake.lock inputs"
