name: "Build and Deploy with Nix"
on:
  push:
    branches: [ master ]
jobs:
  Nix-build-and-Upload:
    runs-on: ubuntu-latest
    steps:
    # Get source code
    - name: Checkout branch to build
      uses: actions/checkout@v4
    # Get Nix in the environment
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    # Questo include i volantini e il gioco delle sagome
    - name: Build zola website
      run: nix build .#sito -L
    - name: Create the config file
      run: |
        printenv RCLONE_CONF > rclone.conf
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
    - name: What's in here
      run: tree -L 2
    - name: Check rclone config and connectivity
      run: |
        nix run .#rclone -- listremotes --config="rclone.conf"
        nix run .#rclone -- lsd --config="rclone.conf" luogoideale:
    - name: Update to FTP
      run: nix run .#rclone -- sync --config="rclone.conf" -v result luogoideale:/htdocs/
